CREATE TABLE IF NOT EXISTS USER (
    USER_ID INT(50) AUTO_INCREMENT NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    USEREMAIL VARCHAR(50) NOT NULL,
    USERACCOUNTTYPE VARCHAR(20) NULL,
    CONSTRAINT UK_USER_USERNAME UNIQUE (USER_ID),
    CONSTRAINT UK_USER_USEREMAIL UNIQUE (USEREMAIL),
    CONSTRAINT PK_USER_USER_ID PRIMARY KEY (USER_ID)
) ENGINE = InnoDB ROW_FORMAT = DEFAULT;

INSERT INTO USER(USERNAME, PASSWORD, USEREMAIL, USERACCOUNTTYPE) VALUES ('admin','adm!n','admin@moviefixddl.com','ADMIN');

CREATE TABLE IF NOT EXISTS MOVIE (
    MOVIE_ID INT(50) AUTO_INCREMENT NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    YEAR INT NOT NULL,
    RATED VARCHAR(10) NULL,
    RELEASED VARCHAR(15) NOT NULL,
    RUNTIME VARCHAR(10) NOT NULL,
    GENRE VARCHAR(100) NOT NULL,
    DIRECTOR VARCHAR(50) NOT NULL,
    WRITER VARCHAR(100) NOT NULL,
    ACTORS VARCHAR(400) NOT NULL,
    PLOT VARCHAR(1000) NOT NULL,
    LANGUAGE VARCHAR(150) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL, 
    AWARDS VARCHAR(150) NULL,
    POSTER VARCHAR(400) NOT NULL,
    METASCORE INT NULL,
    IMDBID VARCHAR(20) NULL,
    IMDBRATING FLOAT NULL,
    IMDBVOTES  INT NULL,
    TYPE VARCHAR(50) NOT NULL,
    CONSTRAINT UK_MOVIE_TITLE UNIQUE (TITLE),
    CONSTRAINT UK_MOVIE_POSTER UNIQUE (POSTER),
    CONSTRAINT UK_MOVIE_IMDBID UNIQUE (IMDBID),
    CONSTRAINT PK_MOVIE_MOVIE_ID PRIMARY KEY (MOVIE_ID)
) ENGINE = InnoDB ROW_FORMAT = DEFAULT;

CREATE TABLE IF NOT EXISTS RATING (
    RATING_ID INT(50) AUTO_INCREMENT NOT NULL,
    USERRATING double NOT NULL,
    MOVIE_ID INT(50) NOT NULL,
    USER_ID INT(50) NOT NULL,
    CONSTRAINT PK_RATING_RATING_ID PRIMARY KEY (RATING_ID),
    CONSTRAINT FK_RATING_MOVIE_ID FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE (MOVIE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RATING_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID) ON DELETE CASCADE
) ENGINE = InnoDB ROW_FORMAT = DEFAULT;


CREATE TABLE IF NOT EXISTS COMMENT (
    COMMENT_ID INT(50) AUTO_INCREMENT NOT NULL,
    MESSAGE VARCHAR(1000) NOT NULL,
    MOVIE_ID INT(50) NOT NULL,
    USER_ID INT(50) NOT NULL,
    CONSTRAINT PK_COMMENT_COMMENT_ID PRIMARY KEY (COMMENT_ID),
    CONSTRAINT FK_COMMENT_MOVIE_ID FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE (MOVIE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_COMMENT_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID) ON DELETE CASCADE
) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
